# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2ad17ba57f90bc507af625b440a13f4"
name = "tier-pricing-function"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Required for managing discounts and reading function data
scopes = "read_discounts,write_discounts,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
