api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "tier-pricing-discount"
type = "function"
uid = "7ecfb76a-30df-8559-f216-fb5ceda8e0d15480fff5"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/tier-pricing-discount.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
